export const EMOJIS = {
  PLAY: '▶️',
  PAUSE: '⏸️',
  STOP: '⏹️',
  SKIP: '⏭️',
  PREVIOUS: '⏮️',
  LOOP: '🔁',
  LOOP_TRACK: '🔂',
  SHUFFLE: '🔀',
  VOLUME: '🔊',
  VOLUME_MUTE: '🔇',
  MUSIC: '🎵',
  QUEUE: '📋',
  ADD: '✅',
  ERROR: '❌',
  WARNING: '⚠️',
  SEARCH: '🔍',
  CLOCK: '⏰',
  WAVE: '👋',
  EMPTY: '📭',
  LYRICS: '📝',
  STAR: '⭐',
  LEFT: '⬅️',
  RIGHT: '➡️',
};
